// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_uYjKSlje_KtdoOBN57UFoK0-orZwrpw',
    appId: '1:607408458720:android:32111c3449e9c4bc403985',
    messagingSenderId: '607408458720',
    projectId: 'fir-series-17e3a',
    storageBucket: 'fir-series-17e3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8kSl8AuTIzXZnccZkS7khhFY3OZvsaHw',
    appId: '1:607408458720:ios:a804695ed6d529af403985',
    messagingSenderId: '607408458720',
    projectId: 'fir-series-17e3a',
    storageBucket: 'fir-series-17e3a.appspot.com',
    androidClientId: '607408458720-bgpilng268m7lrtcg93lih80ff0kpgv0.apps.googleusercontent.com',
    iosClientId: '607408458720-scc386hi12c617jjpjo0d63trvcvddo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
